{
  pkgs,
  pkgs-latest,
  inputs,
  system,
  ...
}:
with pkgs;
with inputs;
[
  wget
  pkgs-latest.zed-editor
  pkgs-latest.ghostty
  pkgs-latest.zls
  pkgs-latest.cider
  pkgs-latest.dms-shell
  pkgs-latest.matugen
  adw-gtk3
  adwaita-qt
  adwaita-qt6
  qt6ct
  extundelete
  postgresql
  cloudflare-warp
  wasmtime
  ntfs3g
  git
  eza
  bat
  neovim
  wayland-pipewire-idle-inhibit
  gummi
  rustup
  go
  fishMinimal
  localsend
  telegram-desktop
  btop
  httpie
  rquickshare
  spotify
  gh
  fastfetchMinimal
  swww
  libreoffice
  lutris
  wineWowPackages.waylandFull
  winetricks
  gitMinimal
  lazygit
  lazydocker
  xwayland-satellite
  easyeffects
  wl-clipboard
  geoclue2
  cliphist
  hyprlock
  starship
  evolve-core
  gradience
  nodejs_24
  pnpm
  texliveTeTeX
  nasm
  gcc15
  glibc
  glibc.dev
  glibc.static
  llvmPackages.clang
  llvmPackages.libclang
  llvmPackages.llvm
  # aws-lc
  pkg-config
  gnumake
  cmake
  rust-bindgen
  openssl
  protobuf
  pkgconf
  docker-compose
  figma-linux
  figma-agent
  vlc
  rustls-libssl
  yazi
  stow
  jujutsu
  fishPlugins.wakatime-fish
  # fishPlugins.sponge
  fishPlugins.gruvbox
  quickshell.packages.${system}.default
  zen-browser.packages."${system}".default
  bibata-cursors
  gtk-engine-murrine
  gnome-tweaks
  kitty
  kitty-img
  kittysay
  libsForQt5.qt5ct
  qt6ct
  qt6.qtwayland
  kdePackages.qt5compat
  libsForQt5.qt5.qtgraphicaleffects
  qt6Packages.qtstyleplugin-kvantum
  kdePackages.qtbase
  kdePackages.qtdeclarative
  kdePackages.qtmultimedia
  kdePackages.qqc2-desktop-style
  kdePackages.sonnet
  kdePackages.kirigami
  kdePackages.kirigami-addons # Not sure if this is needed
  fuzzel
  fprintd-tod
  python313Full
  python313Packages.pip
  libnotify
  dart-sass
  material-symbols
  (ignis.packages.${pkgs.system}.default.override {
    enableAudioService = true;
    enableNetworkService = true;
    enableRecorderService = true;
    enableBluetoothService = true;
    useDartSass = true;
    extraPackages = [
      python313Packages.psutil
      python313Packages.jinja2
      python313Packages.pillow
      python313Packages.materialyoucolor
    ];
  })
  ignis
  zig-overlay.packages.${system}.default
  wayland-pipewire-idle-inhibit
  aseprite
  alsa-lib.dev
  gdb
  brave
  tradingview
  freecad
  tcpdump
  qemu
  nushell
  b3sum
  opencode
  wabt
  helix
  wakatime
  vimPlugins.avante-nvim
  SDL2
  SDL2_ttf
  SDL2_image
  SDL2_mixer
  SDL2_gfx
  SDL2_net
  SDL2_Pango
  tmux
  lilex
  nixd
  nil
  discord
  inkscape
  ghidra-bin
  tiled
  ladybird
  love
  natscli
  nats-server
  just
  buffrs
  ripgrep
  lldb
]
